RPI_CASTA
  AS (
  SELECT
    CASE
      WHEN RPI.ROBC_T12 < '2021-03-21' THEN NULL
      ELSE RPI.ROBC_T12
    END AS ROBC_T12,
    RPI.DT,
    RPI.EFF_DT,
    RPI.END_DT,
    RPI.SEGMENT,
    RPI.OBLIGOR_LEVEL_2_NAME,
    RPI.OBLIGOR_LEVEL_4_NAME,
    RPI.COMMITMENTS,
    RPI.BLENDED_CAPITAL,
    RPI.ECONOMIC_CAPITAL,
    RPI.GROSS_REVENUE_T12,
    RPI.LOAN_LOSS_PROVISION_EXPENSE_T12,
